id: A28A6B28D
title: 'The Lotus Net: A Sang Offering to the Mighty Lotus Ḍākinī, Kurukullā'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:06:30.599236
  last_modified_at: 2022-03-01 04:06:30.599239
