id: A28A6B28D
title: A Sādhana of Kurukullā from the Tidro Dharma Cycle
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:06:30.591512
  last_modified_at: 2022-03-01 04:06:30.591519
