id: A28A6B28D
title: Short Sang Offering to Kurukullā
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:06:30.595516
  last_modified_at: 2022-03-01 04:06:30.595519
